[package]
name = "cooklang"
version = "0.7.1"
edition = "2021"
authors = ["Zheoni <zheoni@outlook.es>"]
description = "Cooklang parser with opt-in extensions"
license = "MIT"
keywords = ["cooklang", "cooking", "recipes"]
categories = ["parser-implementations"]
repository = "https://github.com/cooklang/cooklang-rs"
readme = "README.md"

[dependencies]
anyhow = "1.0"
bitflags = { version = "2", features = ["serde"] }
regex = "1"
serde = { version = "1", features = ["derive", "rc"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
url = { version = "2", features = ["serde"] }
pest = { version = "2", optional = true }
pest_derive = { version = "2", optional = true }
indexmap = { version = "2", features = ["serde"] }
emojis = "0.6"
toml = { version = "0.7", optional = true }
once_cell = "1"
enum-map = { version = "2", features = ["serde"] }
humantime = "2"
tracing = "0.1"
ariadne = "0.3"
either = "1.8"
finl_unicode = { version = "1.2", features = ["categories"], default-features = false }
smallvec = { version = "1", features = ["serde"] }
uniffi = { git = "https://github.com/mozilla/uniffi-rs", branch = "main" }

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.9"
criterion = "0.5"
test-case = "=3.1.0"
indoc = "2.0.3"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", features = ["bindgen-tests"], branch = "main" }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", features= ["build"], branch = "main" }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "cooklang"

[features]
default = ["bundled_units", "aisle"]
bundled_units = ["dep:toml"]
aisle = ["dep:pest", "dep:pest_derive"]
bindings = []

[[bench]]
name = "parse"
harness = false

[[bin]]
# workaround: https://mozilla.github.io/uniffi-rs/tutorial/foreign_language_bindings.html#creating-the-bindgen-binary
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "src/uniffi-bindgen.rs"
required-features = ["bindings", "uniffi/cli"]

[workspace]
members = [".", "playground"]
