[package]
name = "cooklang"
version = "0.9.0"
edition = "2021"
authors = ["Zheoni <zheoni@outlook.es>"]
description = "Cooklang parser with opt-in extensions"
license = "MIT"
keywords = ["cooklang", "cooking", "recipes"]
categories = ["parser-implementations"]
repository = "https://github.com/cooklang/cooklang-rs"
readme = "README.md"

[dependencies]
bitflags = { version = "2", features = ["serde"] }
regex = "1"
serde = { version = "1", features = ["derive", "rc"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
url = { version = "2", features = ["serde"] }
pest = { version = "2", optional = true }
pest_derive = { version = "2", optional = true }
indexmap = { version = "2", features = ["serde"] }
emojis = "0.6"
toml = { version = "0.8", optional = true }
once_cell = "1"
enum-map = { version = "2", features = ["serde"] }
tracing = "0.1"
ariadne = "0.3"
either = "1.8"
finl_unicode = { version = "1.2", features = ["categories"], default-features = false }
smallvec = { version = "1", features = ["serde"] }

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.9"
criterion = "0.5"
test-case = "3.2.1"
indoc = "2.0.3"

[features]
default = ["bundled_units", "aisle"]
bundled_units = ["dep:toml"]
aisle = ["dep:pest", "dep:pest_derive"]

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "convert"
harness = false

[workspace]
members = [".", "playground", "bindings"]
