[si.prefixes]
kilo = []
hecto = []
deca = []
deci = []
centi = []
milli = ["mili"]

[extend.units]
l = { names = ["litro", "litros"] }
c = { names = ["taza", "tazas"] }
"fl oz" = { names = ["onza líquida", "onzas líquidas"] }
gal = { names = ["galón", "galones"] }
pint = { names = ["pinta", "pintas"] }
quart = { names = ["cuarto", "cuartos"] }
m = { names = ["metro", "metros"] }
foot = { names = ["pie", "pies"] }
inch = { names = ["pulgada", "pulgadas"] }
gram = { names = ["gramo", "gramos"] }
kilogram = { aliases = ["kilo", "kilos"] }
ounce = { names = ["onza", "onzas"] }
pound = { names = ["libra", "libras"] }
s = { names = ["segundo", "segundos"] }
min = { names = ["minuto", "minutos"] }
h = { names = ["hora", "horas"] }
d = { names = ["día", "días"] }
